name: Build and Deploy

on:
  push:
    branches: [ main ]  # 根据你的分支名调整

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # 与你的Gemfile一致

      - name: Install dependencies
        run: |
          bundle install

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --baseurl "/blog"
